### ISSUE TITLE
No module named botasaurus.detectors

### ISSUE THREAD

**Issue by B33pl0p** [omkarcloud/amazon-scraper#3]
Followed the process of cloning, installing requirements and then running main.py, got this error:
Traceback (most recent call last):
  File "/workspace/amazon-scraper/main.py", line 1, in <module>
    from src import Amazon
  File "/workspace/amazon-scraper/src/__init__.py", line 1, in <module>
    from .amazon_scraper import Amazon
  File "/workspace/amazon-scraper/src/amazon_scraper.py", line 3, in <module>
    from .write_output import write_output
  File "/workspace/amazon-scraper/src/write_output.py", line 2, in <module>
    from botasaurus.decorators import print_filenames
ModuleNotFoundError: No module named 'botasaurus.decorators'

I also tried in my local machine inside virtual environment but still got the same error

**Comment by moeezali2375** [comment]
did you solve this yet ?

**Comment by baarathsrinivas** [comment]
seems like it got renamed as below
from botasaurus.decorators_common import print_filenames
