### ISSUE TITLE
name 'request' is not defined

### ISSUE THREAD

**Issue by baarathsrinivas** [omkarcloud/amazon-scraper#4]
Traceback (most recent call last):
  File "E:\code\amazon-scraper\main.py", line 1, in <module>
    from src import Amazon
  File "E:\code\amazon-scraper\src\__init__.py", line 1, in <module>
    from .amazon_scraper import Amazon
  File "E:\code\amazon-scraper\src\amazon_scraper.py", line 5, in <module>
    from .search import FAILED_DUE_TO_CREDITS_EXHAUSTED, FAILED_DUE_TO_NO_KEY,FAILED_DUE_TO_NOT_SUBSCRIBED, FAILED_DUE_TO_UNKNOWN_ERROR, get_product, search
  File "E:\code\amazon-scraper\src\search.py", line 94, in <module>
    @request(**default_request_options)
NameError: name 'request' is not defined. Did you mean: 'requests'?

**Comment by baarathsrinivas** [comment]
adding following import statement worked for me 
from botasaurus.request_decorator import *
